language: java
jdk:
- openjdk8

branches:
  only:
  - master
  - development

before_install:
  - echo "$TNO_DOCKER_PASSWORD" | docker login app-docker136.hex.tno.nl -u "$TNO_DOCKER_USERNAME" --password-stdin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install: gradle install buildMyAppImage dockerBuildImage

script:
- export VERSION=$(grep "helloWorldVersion" ./.shared/libraries.gradle | awk '{print $3}' | tr -d \')
# - cd TS_HelloWorld
# - docker build --build-arg version=$VERSION -t ivct/ts-helloworld:$TRAVIS_BRANCH-latest -t ivct/ts-helloworld:$TRAVIS_BRANCH-$VERSION .
- if [ $TRAVIS_BRANCH == "master" ]; then docker tag ivct/ts-helloworld:$TRAVIS_BRANCH-$VERSION ivct/ts-helloworld:$VERSION && docker tag ivct/ts-helloworld:$TRAVIS_BRANCH-$VERSION ivct/ts-helloworld:latest; fi
- docker push ivct/ts-helloworld
- if [ $TRAVIS_BRANCH == "master" ]; then docker tag ivct/helloworld:$TRAVIS_BRANCH-$VERSION ivct/helloworld:$VERSION && docker tag ivct/helloworld:$TRAVIS_BRANCH-$VERSION ivct/helloworld:latest; fi
- docker push ivct/helloworld

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
