== The HelloWorld Federation Concept

The HelloWorld federation was presented at the very beginning of the HLA developments. As so many "hello world" applications, it was designed to give very simple but fully functional example for a distributed simulation.

The idea is simple and it follows the HLA federation paradigm in a straight forward way. Each instance of the helloWorld application implements a *Country* object, which is represented by its *Ambassador*, and it is joining a *HelloWorld* federation. So the HelloWorld federation is a set of countries, where each country is simulated by one helloWorld application.

=== The Behavior Model

The original definition in the early HelloWorld implementations, there are no strict requirements on _correct_ behavior. So almost anything a helloWorld federate could do or not do, would be fine. It could create a Country object or it could not. It could create one or many objects, or it could create none. It could give them a Name or it could not. It could let the Population grow or shrink. It could send Messages or it could not.

While this is a perfectly reasonable approach to demonstrate the HLA features, it might be not enough to ensure that HelloWorld federates from different developers are building a well interworking federation. If federates must comply with certain interoperability patterns, it is important that these patterns are unambiguously identified.

For the sake of this tutorial we introduced two interoperability requirements to define a specific behavior pattern.

* One is that the population of a country shall grow at a specific rate. More specifically the difference between two updates of the countries' population attribute shall be greater than null, but less than a given percentage.

* Two is that each country is expected to respond to a greeting messages along some predefined "diplomatic" rules. Technically that means to respond to *Communication* interactions with a response interaction in a predefined format.

These interoperability requirements are defined in the *HelloWorld* badge, which is explained in the next chapter <<2-2-hw-interoperability-badge.adoc#, HelloWorld Interoperability Badge>>

=== The Country Object

The *Country* object is used to model the country simulated by a helloWorld application. When entering the HelloWorld federation, the application will create its own Country object instance. It has a country *Name* and a country *Population* attribute.


[source, xml]
----
<objectClass>
   <name>Country</name>
   <sharing>Neither</sharing>
   <attribute>
      <name>Name</name>
      <dataType>HLAunicodeString</dataType>
      <updateType>Conditional</updateType>
      <ownership>DivestAcquire</ownership>
      <sharing>Neither</sharing>
      <transportation>HLAreliable</transportation>
      <order>Receive</order>
   </attribute>
   <attribute>
      <name>Population</name>
      <dataType>HLAunicodeString</dataType>
      <updateType>Conditional</updateType>
      <ownership>DivestAcquire</ownership>
      <sharing>Neither</sharing>
      <transportation>HLAreliable</transportation>
      <order>Receive</order>
   </attribute>
</objectClass>
----

=== The Country Interaction

To make the HelloWorld federation a bit more interesting, the interaction class *Communication* was introduced. This interaction consists of a *Message* from a named *Sender*, which is send from one federate into the federation to be received by all other federates.

[source, xml]
----
<interactionClass>
   <name>Communication</name>
   <sharing>Publish</sharing>
   <transportation>HLAreliable</transportation>
   <order>Receive</order>
   <semantics>Communication</semantics>
   <parameter>
      <name>Message</name>
      <dataType>HLAunicodeString</dataType>
      <semantics>Contents of message</semantics>
   </parameter>
   <parameter>
      <name>Sender</name>
      <dataType>HLAunicodeString</dataType>
      <semantics>The name of the person that sent the message.</semantics>
   </parameter>
</interactionClass>
----
