== Test Suite Definition

A test suite is defined by a JSON definition file, like the TS-HelloWorld-2019 test suite below. It defines the id, name, version of the test suite and it contains a description filed to explain the purpose of the test suite. It also defines two runtime folder, one for the jar files and one to start the test cases.

The capabilities of the test suites are defined by the attribute `testcases`. It is the list of test cases which are contained in the test suite. Each test cases is defined by its fully qualified class name (`TC`), by a description and finally by a list of interoperability requirements (`IR`), testes by the test case.

.The TS-HelloWorld-2019 Test Suite Definition
[source, yaml]
----
{
  "id": "TS-HelloWorld-2019",
  "version": "2.0.0",
  "name": "HelloWorld Tutorial Badge",
  "description": "This is a simple example for a testsuite to test
                  the compliance of an federate to the hello world federation.",
  "tsRunTimeFolder": "TS_HelloWorld-2.0.0/bin",
  "tsLibTimeFolder": "TS_HelloWorld-2.0.0/lib",
  "testcases": [
  {
    "TC": "de.fraunhofer.iosb.tc_helloworld.TC0001",
    "IR": ["IR-HW-0001"],
    "description": "Test population growing rate"
  },
  {
    "TC": "de.fraunhofer.iosb.tc_helloworld.TC0002",
    "IR": ["IP-HW-0002"],
    "description": "Test inter-country communication"
  }]
}
----

In the example of the HelloWorld test suite, we have two test cases, `IR-HW-0001` and `IR-HW-0001`. Each test cases will test exactly one interoperability requirement. This is the recommended way, because it simplifies the arrangement of test interoperability requirements into different badges. And it also simplifies the design of the test cases, as their scope is limited to only one requirement.
