== What is a Test Suite?

=== Test Suites as Containers for Test Cases

From a programmer's point of view, a test case is piece of code within a framework of supporting code assets. The test case is designed to verify a very specific behavior pattern within a federation agreement. The supporting code assets are used for the more generic tasks, like subscribing to certain interactions or setting up test objects.

In most cases the federation agreement covers many individual patterns. In such cases the test case developer has to implement many test cases and it makes sense to share the generic supporting code assets and also to have all test cases within one project context. From this comes the concept of a *Test Suite*.

A *Test Suite* is a collection of test cases within a common code environment and a build script to compile, test and build a software container to be deployed into a IVCTool installation. While not strictly required, it is helpful to have documentation of the test suite, and a simple federate that can be used as a placeholder for a System under Test.


=== Test Suite Definition

For the IVCTool integration, a test suite is defined by a JSON definition file, like the `TS-HelloWorld-2019.json` test suite below. It defines the id, name, and version of the test suite, and it contains a description field to explain the purpose of the test suite. It also defines two runtime folders; one for the jar files, and one to start the test cases.

The capabilities of the test suite are defined by the attribute `testcases`. It is the list of test cases which are contained in the test suite. Each test cases is defined by its fully qualified class name (`TC`), a description, and a list of interoperability requirements (`IR`), tested by the test case.

.The TS-HelloWorld-2019 Test Suite Definition
[source, yaml]
----
{
  "id": "TS-HelloWorld-2019",
  "version": "2.0.0",
  "name": "HelloWorld Tutorial Badge",
  "description": "This is a simple example for a testsuite to test
                  the compliance of an federate to the hello world federation.",
  "tsRunTimeFolder": "TS_HelloWorld-2.0.0/bin",
  "tsLibTimeFolder": "TS_HelloWorld-2.0.0/lib",
  "testcases": [
  {
    "TC": "de.fraunhofer.iosb.tc_helloworld.TC0001",
    "IR": ["IR-HW-0001"],
    "description": "Test population growing rate"
  },
  {
    "TC": "de.fraunhofer.iosb.tc_helloworld.TC0002",
    "IR": ["IP-HW-0002"],
    "description": "Test inter-country communication"
  }]
}
----

In the example of the HelloWorld test suite, we have two test cases, `IR-HW-0001` and `IR-HW-0001`. Each test cases will test exactly one interoperability requirement. This is the recommendedpractice because it simplifies the reuse of tests in multiple badges. It also simplifies the design of the test cases, as their scope is limited to only one requirement.
