== Where to start when writing a test case?

As explained earlier, conceptually the starting point of every test cases is an *Interoperability Requirement (IR)*. That can be seen as the specification for the test case implementation. In some cases there might be *Abstract Test Case* provided for a IR. That will be the blueprint of the code you have to write, to create an *Executable Test Case (ETC)*.

There are some requirements an ETC has to fulfill, in order to be useable by the IVCTool test engine. These are things like the implement the IVCTool test case library functions, as the interface class `AbstractTestCase`, or the way it is packaged into a jar file and containerized into a docker image. While you are free how to do this, we recommend to follow the example of the HelloWorld test suite, in order to avoid a confusing variety of test suites structures to be maintained for the IVCTool installations.

In the next steps we will walk you through the steps to create a test suite.

=== Step 1: Create a Gradle Test Suite Project

The IVCTool framework software is build with the link:https://gradle.org/[Gradle Build Tool]. There are several great link:https://gradle.org/guides/[Tutorials and Guides] to learn more about using gradle, and we encourage you got have a look to get some basic understanding on how this build tool works.

As a quickstart you can use the TS_HelloWorld project as template to start with. An easy way to do this, is to get a copy of the link:https://github.com/IVCTool/TS_HelloWorld[TS_HelloWorld] project. Use the *DownloadZIP* feature, to get clean copy without any references to the git project. That is important, because you don't want to mess with the original github repository. Later on you can create your own github repository, but for that you should start without any references to TS_HelloWorld.

Your copy should contain the following items:

- `TS_HelloWorld/` : This is the folder with test cases.
- `HelloWorld/` : This is folder with an implementation of the test federate.
- `docs/` : folder with documentation files.
- `gradle/` : The gradle wrapper code
- `build.gradle` : The gradle build script
- `settings.gradle` : The gradle build settings for the subprojects
- `gradlew` : The gradle wrapper unix start script
- `gradlew.bat` : The gradle wrapper windows start script
- `LICENSE` : The license to define the code availability
- `README.md` : The top level documentation

.IMPORTANT: If you are using the TS_HelloWorld test suite as a template to create your own test suite, you need to adjust the naming of some folders, as well as the gradle scripts.

-

=== Step 2: Adjust the Test Cases

The test cases are located in the TS_HelloWorld subproject folder. The main items here are the `src` folder with the source code, the `TS_HelloWorld.gradle` script to build distribution packages and a `Dockerfile` for the containerized deployment.

==== Step 2.a: Test Case Parameters

A test cases may need some parameters to specify the test behavior for a given System under Test (SuT). In the case of the HelloWorld test suite it is the growing rate of a country population.

These parameters will be set by the IVCTool operator, before test case is started. For that purpose the IVCTool user interface needs to know which parameters are required, i.e. it needs a template for the parameters. This template must be provided by the test suite as a resource file with the name `TS_HelloWorld/src/main/resources/TcParams.json`.

If other resource are required for some test case, they need to be added into the resource folder. For the HelloWorld test suite this is the FOM file for the HelloWorld federation.

The Gradle build script will include all resource files into the distribution package. The IVCTool will then copy these resource files of allow the operator to edit the values before starting a test case.

==== Step 2.b: Test Case Implementation

The actual implementation of the test cases is located in the `TS_HelloWorld/src/main/java` folder. Inside this folder you will find subfolders with the java code packages. The HelloWorld test suite is using packages name:

* `de/fraunhofer/iosb/tc_helloworld` : For the two test cases TC0001 and TC0002.
* `de/fraunhofer/iosb/tc_lib_helloworld` : For some helper classed used by both test cases.

==== Step 2.c: Build the Test Cases

To build the test cases you are using the gradle wrapper command. The build tasks to be used can be seen the command `gradlew tasks`. The most important ones are:

* `gradlew build` : This task will compile the code and it will create the libraries

=== Step 3: Deploy the Test Suite container into a IVCTool installation

The test cases can not be executed as stand-alone applications. They need to be deployed into a run-time configuration in a IVCTool installation. Currently where are two different ways to setup such a run-time configuration. It can be included into a docker configuration, or it can used in non-containerized version directly on a file system. The docker option is the most convenient way to distribute a test suite and the plain file installation is preferable in a development environment.

==== Step 3.a: Docker Deployment

If you are using the IVCTool installation on a docker based installation, you need to build the test suite as a docker container.

* `gradlew dockerBuildImage`: This task will create a docker image in your locale docker engine.

This will create a docker image which will be used in the compose files to startup the IVCTool

----
$ docker image ls| grep ts-helloworld
ivct/ts-helloworld                           2.0.0                     a76c25bc09a7        17 minutes ago      1.18MB
----

Detailed information on docker based deployment of the IVCTool can be found in the https://github.com/IVCTool/IVCT_Operation/blob/develop/docs/src/home.adoc[IVCTool/IVCT_Operation] repository.

==== Step 3.b: Plain File System Deployment

* `gradlew distTar`: This task will create a tar archive with all lib files.
* `gradlew distZip`: This task will create a zip archive with all lib files.


The content of these archives should be the following:
----
./TS_HelloWorld-2.0.0:
bin/  lib/

./TS_HelloWorld-2.0.0/bin:
TS_HelloWorld*  TS_HelloWorld.bat

./TS_HelloWorld-2.0.0/lib:
TS_HelloWorld-2.0.0.jar
----

The extracted archive need to be deployed into IVCTool runtime folder for the test suites. The location of this folder is defined by `IVCT_TS_HOME_ID` setting, either in your IVCT properties file or as environment variable (see https://github.com/IVCTool/IVCT_Framework/blob/development/docs/src/2-8-IVCT_Configuration.adoc[Configuration of the IVCTool] for more information).
