== 3-6_Versioncheck-between-TestCases-and-Runtime-environment

=== Compile-time-version - Information in the TestCases /TestSuites
While  compiling the TestCase,  a specific IVCT-version (and TC.lib) is used. +
This version  should be documented  'in'  the TestCases. +
The information is entered manually, before releasing a new version, in the gradle file libraries.gradle . (e.g. ivctVersion = '2.1.1' ) +
Because at runtime this libraries.gradle is not present, it will be written by the gradle build process 
in a  property file  "testCaseBuild.properties",   which is found  in the  TestSuite-jar file. +
We put the task to write the version-information  from libraries.gradle  to  testCaseBuild.properties
in the  TestsuiteName.gradle file in the TestSuite specific folder. +
If  someone use another build System for TestCases, it would be essential  to pass the version information in another way to  the  testCaseBuild.properties

=== Informations about  compatible Versions   in  TestEngine   (available  at runtime)
In the same manner as we documented the IVCT-version in TestCases, 
the information which versions of the TC.lib should be compatible to 'this'  version of TestEngine is processed. +
A list of compatible versions (array/hasmap) ist written manually in the libraries.gradle  of the IVCT_Framework: +
compatibleVersions = ['3.0.0':'compatible','2.2.2-SNAPSHOT':'compatible', '2.1.1':'compatible', '2.1.0':'incompatible'] +
In TC.exec/TC.exec.gradle a task is defined which writes the informations from the libraries.gradle  to the property-File  compatibleVersions.properties.

=== Compare Versions while running a TestCase
As all TestCases are subclasses of  AbstractTestCase (part of  TC.lib),  the method to read  the IVCT-Version-information  at runtime  ist situated  here. + 
Thus every TestCase has a method  getIVCTVersion()  which reads the value for  "ivctVersion"   from  testCaseBuild.properties. +
It is the TestEngine which calls for each testcase this method  and uses the gotten String  to create a new  instance of  the class  IVCTVersionCheck. +
IVCTVersionCheck  checks  this value against  the list it reads from the compatibleVersions.properties
to  evaluate if the Versions are compatible. +
In case of  no  positive match,  it  throw a special exception.
