== Operator Request

=== Motivation

Some testcases require a dynamic reaction from the SUT which cannot be automated. The test case writer knows what the SUT has to do at a certain point of the test: the testcase needs to make a request to the SUT Operator and wait until the SUT Operator confirms that the required action or configuration has been performed.

=== Usage

The method sendOperatorRequest(String operatorRequest) provided by IVCT package TC.lib can be called within a testcase to send the operatorRequest to the GUI/OperatorRequestMonitor processes. The operatorRequest will be shown on the GUI/OperatorRequestMonitor and the testcase will wait until the SUT Operator confirms the request on the OperatorRequestMonitor console.

=== Implementation

Each testcase must have a unique identification associated to it. The sendOperatorRequest(String operatorRequest) will put the unique testcase identifier and the operatorRequest into a JSON string and send it to the OperatorRequestMonitor via the JMS bus. The method will wait on a semaphore halting the testcase until a confirmation by SUT Operator has been received from the OperatorRequestMonitor. Upon receiving the confirmation with the corresponding unique testcase identifier, the TC.exec TestEngine will release the semaphore associated with the testcase, allowing the testcase to continue.

=== Example: Test Case / SUT Synchronization

Each testcase has the requirement either that the SUT is running before or after the testcase is started. The testcase may need to observe actions at the beginning of an execution, in this case a SUT that is already running may have already completed this phase making the test useless. If the testcase makes observations for a limited period of time, the SUT must already be running or the testcase may time out before any observation is made.

In either case, it is useful to make a request to the test operator to ensure that the SUT is correctly started for the test. The sendOperatorRequest(String operatorRequest) will be placed at beginning the preambleAction() method of the testcase to achieve the testcase/SUT synchronization.
