FROM hlacontainers/lrc:vtmak-skeleton-centos7

ARG version

ADD ./build/distributions/HelloWorld-${version}.tar /root/application/

ADD ./docker/start.sh /root/application/start.sh

RUN ln -s /root/application/HelloWorld-${version} /root/application/HelloWorld

RUN chmod a+x /root/application/start.sh

ENV LRC_ENTRYPOINT=/root/application/start.sh
